import { IntelligenceReport, TechnologyItem } from '../types';
import { MOCK_REPORTS, MOCK_TECHNOLOGIES } from '../data/technologiesData';

export class ReportGeneratorService {
  private reports: IntelligenceReport[] = [...MOCK_REPORTS];

  public getAllReports(): IntelligenceReport[] {
    return this.reports;
  }

  public generateReport(period: IntelligenceReport['period'], customTechnologies: TechnologyItem[] = MOCK_TECHNOLOGIES): IntelligenceReport {
    const today = new Date().toISOString().split('T')[0];
    const topTechNames = customTechnologies
      .sort((a, b) => b.scores.overallOpportunityScore - a.scores.overallOpportunityScore)
      .slice(0, 3)
      .map(t => `${t.technologyName} (${t.scores.overallOpportunityScore}/100 Score)`);

    const newReport: IntelligenceReport = {
      id: `rep-${period.toLowerCase()}-${Date.now()}`,
      title: `${period} AI Market & Future Technology Intelligence Briefing`,
      period: period,
      generatedDate: today,
      executiveSummary: `Automated ${period.toLowerCase()} analysis across 50 global data feeds indicates accelerated convergence between Agentic AI software networks, embodied humanoid robotics, and clean baseload energy systems. Weak signal detection reveals a 210% surge in open-source multi-agent code repos and a 165% increase in quantum key distribution patents.`,
      topExplodingTech: topTechNames,
      keyWeakSignals: [
        'Sub-milliwatt neuromorphic processing units running quantized 7B LLMs on-device.',
        'High-density 24 DoF tactile robot hands reaching production cost parity.',
        'Compact high-field Tokamak fusion reactors sustaining Q>2.4 net energy gain.'
      ],
      vcInvestmentShift: `Venture Capital investment in ${period.toLowerCase()} cycles has shifted 44% towards deeptech infrastructure, with multi-agent security frameworks and post-quantum cryptography commanding highest valuations.`,
      workforceImplications: `Strong labor market expansion for Agentic AI Systems Architects ($180k-$340k) and Embodied AI Fleet Supervisors. Automation risk for routine white-collar code generation is elevated to 65%.`,
      strategicRecommendations: [
        'Establish internal AI Agent compliance guardrails before scaling multi-agent production pipelines.',
        'Initiate post-quantum cryptography auditing across enterprise security endpoints.',
        'Monitor pilot deployments of humanoid general-purpose robotics in logistics facilities.'
      ],
      citationsCount: 165
    };

    this.reports.unshift(newReport);
    return newReport;
  }

  public exportReportAsMarkdown(report: IntelligenceReport): string {
    return `# ${report.title}
**Period:** ${report.period} | **Generated Date:** ${report.generatedDate} | **Citations:** ${report.citationsCount}

---

## Executive Summary
${report.executiveSummary}

---

## Top Exploding Technologies
${report.topExplodingTech.map(t => `- **${t}**`).join('\n')}

---

## Key Weak Signals Detected
${report.keyWeakSignals.map(s => `- ⚡ ${s}`).join('\n')}

---

## VC & Sovereign Investment Shift
${report.vcInvestmentShift}

---

## Workforce & Future Jobs Implications
${report.workforceImplications}

---

## Strategic Recommendations
${report.strategicRecommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---
*Report automatically generated by the Future Market Predictor Platform AI Agent Network.*
`;
  }
}

export const reportGeneratorService = new ReportGeneratorService();
